### ISSUE TITLE
Can i get entire data from source for map visualization

### ISSUE THREAD

**Issue by tirumalavasu** [Zoomdata/custom-regions-visualization#2]
So far, zoomdata is providing only latitude and longitude data to controller (custom chart). Is there anyway to get all the source data, I mean all the fields just as like in Raw Data Table.

**Comment by WerlingM** [comment]
Since you mention latitude and longitude I assume you are referring to the Map: Markers chart in Zoomdata.  This chart (Custom Regions) is based on a different approach than the Map Markers chart.  Custom Regions relies on a set of GeoJSON polygons to define the locations, which are then matched with values returned from a Zoomdata query.

For questions about Map: Markers your best bet is to contact Zoomdata directly (support@zoomdata.com).

**Comment by tirumalavasu** [comment]
Thanks for the help. I got it working. We can query to get all the data from the controller.
